// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/v1/plugin.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginEmpty) Reset() {
	*x = PluginEmpty{}
	mi := &file_api_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEmpty) ProtoMessage() {}

func (x *PluginEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEmpty.ProtoReflect.Descriptor instead.
func (*PluginEmpty) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMetadataRequest) Reset() {
	*x = PluginMetadataRequest{}
	mi := &file_api_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadataRequest) ProtoMessage() {}

func (x *PluginMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetadataRequest.ProtoReflect.Descriptor instead.
func (*PluginMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type PluginMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DocsUrl       string                 `protobuf:"bytes,5,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,7,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMetadata) Reset() {
	*x = PluginMetadata{}
	mi := &file_api_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadata) ProtoMessage() {}

func (x *PluginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetadata.ProtoReflect.Descriptor instead.
func (*PluginMetadata) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginMetadata) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *PluginMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMetadata) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PluginMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginMetadata) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *PluginMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginMetadata) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	LabelSelector string                 `protobuf:"bytes,3,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	Kinds         []string               `protobuf:"bytes,4,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Names         []string               `protobuf:"bytes,5,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_api_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AnalyzeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AnalyzeRequest) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

func (x *AnalyzeRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *AnalyzeRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type PluginFinding struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind            string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Severity        string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Category        string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Summary         string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	Details         string                 `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	Evidence        []string               `protobuf:"bytes,9,rep,name=evidence,proto3" json:"evidence,omitempty"`
	DocsUrl         string                 `protobuf:"bytes,10,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`
	ParentKind      string                 `protobuf:"bytes,11,opt,name=parent_kind,json=parentKind,proto3" json:"parent_kind,omitempty"`
	ParentName      string                 `protobuf:"bytes,12,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	ParentNamespace string                 `protobuf:"bytes,13,opt,name=parent_namespace,json=parentNamespace,proto3" json:"parent_namespace,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginFinding) Reset() {
	*x = PluginFinding{}
	mi := &file_api_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginFinding) ProtoMessage() {}

func (x *PluginFinding) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginFinding.ProtoReflect.Descriptor instead.
func (*PluginFinding) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *PluginFinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginFinding) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PluginFinding) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PluginFinding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginFinding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *PluginFinding) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PluginFinding) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PluginFinding) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *PluginFinding) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *PluginFinding) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *PluginFinding) GetParentKind() string {
	if x != nil {
		return x.ParentKind
	}
	return ""
}

func (x *PluginFinding) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *PluginFinding) GetParentNamespace() string {
	if x != nil {
		return x.ParentNamespace
	}
	return ""
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Findings      []*PluginFinding       `protobuf:"bytes,2,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_api_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AnalyzeResponse) GetFindings() []*PluginFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_v1_plugin_proto protoreflect.FileDescriptor

const file_api_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/plugin.proto\x12\rsre.plugin.v1\"\r\n" +
	"\vPluginEmpty\"\x17\n" +
	"\x15PluginMetadataRequest\"\xdb\x01\n" +
	"\x0ePluginMetadata\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bdocs_url\x18\x05 \x01(\tR\adocsUrl\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x1b\n" +
	"\tread_only\x18\a \x01(\bR\breadOnly\"\xa8\x01\n" +
	"\x0eAnalyzeRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12%\n" +
	"\x0elabel_selector\x18\x03 \x01(\tR\rlabelSelector\x12\x14\n" +
	"\x05kinds\x18\x04 \x03(\tR\x05kinds\x12\x14\n" +
	"\x05names\x18\x05 \x03(\tR\x05names\"\xf5\x02\n" +
	"\rPluginFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12\x18\n" +
	"\adetails\x18\b \x01(\tR\adetails\x12\x1a\n" +
	"\bevidence\x18\t \x03(\tR\bevidence\x12\x19\n" +
	"\bdocs_url\x18\n" +
	" \x01(\tR\adocsUrl\x12\x1f\n" +
	"\vparent_kind\x18\v \x01(\tR\n" +
	"parentKind\x12\x1f\n" +
	"\vparent_name\x18\f \x01(\tR\n" +
	"parentName\x12)\n" +
	"\x10parent_namespace\x18\r \x01(\tR\x0fparentNamespace\"r\n" +
	"\x0fAnalyzeResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x128\n" +
	"\bfindings\x18\x02 \x03(\v2\x1c.sre.plugin.v1.PluginFindingR\bfindings\"g\n" +
	"\x0eHealthResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xf2\x01\n" +
	"\x10ExternalAnalyzer\x12O\n" +
	"\bMetadata\x12$.sre.plugin.v1.PluginMetadataRequest\x1a\x1d.sre.plugin.v1.PluginMetadata\x12H\n" +
	"\aAnalyze\x12\x1d.sre.plugin.v1.AnalyzeRequest\x1a\x1e.sre.plugin.v1.AnalyzeResponse\x12C\n" +
	"\x06Health\x12\x1a.sre.plugin.v1.PluginEmpty\x1a\x1d.sre.plugin.v1.HealthResponseB)Z'github.com/kubebee-com/sre/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_plugin_proto_rawDescOnce sync.Once
	file_api_v1_plugin_proto_rawDescData []byte
)

func file_api_v1_plugin_proto_rawDescGZIP() []byte {
	file_api_v1_plugin_proto_rawDescOnce.Do(func() {
		file_api_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_plugin_proto_rawDesc), len(file_api_v1_plugin_proto_rawDesc)))
	})
	return file_api_v1_plugin_proto_rawDescData
}

var file_api_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_plugin_proto_goTypes = []any{
	(*PluginEmpty)(nil),           // 0: sre.plugin.v1.PluginEmpty
	(*PluginMetadataRequest)(nil), // 1: sre.plugin.v1.PluginMetadataRequest
	(*PluginMetadata)(nil),        // 2: sre.plugin.v1.PluginMetadata
	(*AnalyzeRequest)(nil),        // 3: sre.plugin.v1.AnalyzeRequest
	(*PluginFinding)(nil),         // 4: sre.plugin.v1.PluginFinding
	(*AnalyzeResponse)(nil),       // 5: sre.plugin.v1.AnalyzeResponse
	(*HealthResponse)(nil),        // 6: sre.plugin.v1.HealthResponse
}
var file_api_v1_plugin_proto_depIdxs = []int32{
	4, // 0: sre.plugin.v1.AnalyzeResponse.findings:type_name -> sre.plugin.v1.PluginFinding
	1, // 1: sre.plugin.v1.ExternalAnalyzer.Metadata:input_type -> sre.plugin.v1.PluginMetadataRequest
	3, // 2: sre.plugin.v1.ExternalAnalyzer.Analyze:input_type -> sre.plugin.v1.AnalyzeRequest
	0, // 3: sre.plugin.v1.ExternalAnalyzer.Health:input_type -> sre.plugin.v1.PluginEmpty
	2, // 4: sre.plugin.v1.ExternalAnalyzer.Metadata:output_type -> sre.plugin.v1.PluginMetadata
	5, // 5: sre.plugin.v1.ExternalAnalyzer.Analyze:output_type -> sre.plugin.v1.AnalyzeResponse
	6, // 6: sre.plugin.v1.ExternalAnalyzer.Health:output_type -> sre.plugin.v1.HealthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_plugin_proto_init() }
func file_api_v1_plugin_proto_init() {
	if File_api_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_plugin_proto_rawDesc), len(file_api_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_plugin_proto_goTypes,
		DependencyIndexes: file_api_v1_plugin_proto_depIdxs,
		MessageInfos:      file_api_v1_plugin_proto_msgTypes,
	}.Build()
	File_api_v1_plugin_proto = out.File
	file_api_v1_plugin_proto_goTypes = nil
	file_api_v1_plugin_proto_depIdxs = nil
}
