// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: api/v1/plugin.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExternalAnalyzer_Metadata_FullMethodName = "/sre.plugin.v1.ExternalAnalyzer/Metadata"
	ExternalAnalyzer_Analyze_FullMethodName  = "/sre.plugin.v1.ExternalAnalyzer/Analyze"
	ExternalAnalyzer_Health_FullMethodName   = "/sre.plugin.v1.ExternalAnalyzer/Health"
)

// ExternalAnalyzerClient is the client API for ExternalAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalAnalyzerClient interface {
	Metadata(ctx context.Context, in *PluginMetadataRequest, opts ...grpc.CallOption) (*PluginMetadata, error)
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Health(ctx context.Context, in *PluginEmpty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type externalAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalAnalyzerClient(cc grpc.ClientConnInterface) ExternalAnalyzerClient {
	return &externalAnalyzerClient{cc}
}

func (c *externalAnalyzerClient) Metadata(ctx context.Context, in *PluginMetadataRequest, opts ...grpc.CallOption) (*PluginMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginMetadata)
	err := c.cc.Invoke(ctx, ExternalAnalyzer_Metadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalAnalyzerClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, ExternalAnalyzer_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalAnalyzerClient) Health(ctx context.Context, in *PluginEmpty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ExternalAnalyzer_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalAnalyzerServer is the server API for ExternalAnalyzer service.
// All implementations must embed UnimplementedExternalAnalyzerServer
// for forward compatibility.
type ExternalAnalyzerServer interface {
	Metadata(context.Context, *PluginMetadataRequest) (*PluginMetadata, error)
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	Health(context.Context, *PluginEmpty) (*HealthResponse, error)
	mustEmbedUnimplementedExternalAnalyzerServer()
}

// UnimplementedExternalAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExternalAnalyzerServer struct{}

func (UnimplementedExternalAnalyzerServer) Metadata(context.Context, *PluginMetadataRequest) (*PluginMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method Metadata not implemented")
}
func (UnimplementedExternalAnalyzerServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedExternalAnalyzerServer) Health(context.Context, *PluginEmpty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedExternalAnalyzerServer) mustEmbedUnimplementedExternalAnalyzerServer() {}
func (UnimplementedExternalAnalyzerServer) testEmbeddedByValue()                          {}

// UnsafeExternalAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalAnalyzerServer will
// result in compilation errors.
type UnsafeExternalAnalyzerServer interface {
	mustEmbedUnimplementedExternalAnalyzerServer()
}

func RegisterExternalAnalyzerServer(s grpc.ServiceRegistrar, srv ExternalAnalyzerServer) {
	// If the following call panics, it indicates UnimplementedExternalAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExternalAnalyzer_ServiceDesc, srv)
}

func _ExternalAnalyzer_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalAnalyzerServer).Metadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalAnalyzer_Metadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalAnalyzerServer).Metadata(ctx, req.(*PluginMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalAnalyzer_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalAnalyzerServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalAnalyzer_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalAnalyzerServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalAnalyzer_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalAnalyzerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalAnalyzer_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalAnalyzerServer).Health(ctx, req.(*PluginEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalAnalyzer_ServiceDesc is the grpc.ServiceDesc for ExternalAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sre.plugin.v1.ExternalAnalyzer",
	HandlerType: (*ExternalAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Metadata",
			Handler:    _ExternalAnalyzer_Metadata_Handler,
		},
		{
			MethodName: "Analyze",
			Handler:    _ExternalAnalyzer_Analyze_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ExternalAnalyzer_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/plugin.proto",
}
