// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/v1/sre.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty is used for RPCs whose request has no parameters.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_v1_sre_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{0}
}

type ScanRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion     string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	IncludeNamespaces []string               `protobuf:"bytes,2,rep,name=include_namespaces,json=includeNamespaces,proto3" json:"include_namespaces,omitempty"`
	ExcludeNamespaces []string               `protobuf:"bytes,3,rep,name=exclude_namespaces,json=excludeNamespaces,proto3" json:"exclude_namespaces,omitempty"`
	LabelSelector     string                 `protobuf:"bytes,4,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	Kinds             []string               `protobuf:"bytes,5,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Names             []string               `protobuf:"bytes,6,rep,name=names,proto3" json:"names,omitempty"`
	Analyzers         []string               `protobuf:"bytes,7,rep,name=analyzers,proto3" json:"analyzers,omitempty"`
	MaxConcurrency    int32                  `protobuf:"varint,8,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	// Go duration syntax, for example "30s" or "2m".
	Timeout       string `protobuf:"bytes,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_api_v1_sre_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{1}
}

func (x *ScanRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ScanRequest) GetIncludeNamespaces() []string {
	if x != nil {
		return x.IncludeNamespaces
	}
	return nil
}

func (x *ScanRequest) GetExcludeNamespaces() []string {
	if x != nil {
		return x.ExcludeNamespaces
	}
	return nil
}

func (x *ScanRequest) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

func (x *ScanRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *ScanRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *ScanRequest) GetAnalyzers() []string {
	if x != nil {
		return x.Analyzers
	}
	return nil
}

func (x *ScanRequest) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *ScanRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type ScanScope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion     string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	IncludeNamespaces []string               `protobuf:"bytes,2,rep,name=include_namespaces,json=includeNamespaces,proto3" json:"include_namespaces,omitempty"`
	ExcludeNamespaces []string               `protobuf:"bytes,3,rep,name=exclude_namespaces,json=excludeNamespaces,proto3" json:"exclude_namespaces,omitempty"`
	LabelSelector     string                 `protobuf:"bytes,4,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	Kinds             []string               `protobuf:"bytes,5,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Names             []string               `protobuf:"bytes,6,rep,name=names,proto3" json:"names,omitempty"`
	Analyzers         []string               `protobuf:"bytes,7,rep,name=analyzers,proto3" json:"analyzers,omitempty"`
	MaxConcurrency    int32                  `protobuf:"varint,8,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	Timeout           string                 `protobuf:"bytes,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScanScope) Reset() {
	*x = ScanScope{}
	mi := &file_api_v1_sre_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanScope) ProtoMessage() {}

func (x *ScanScope) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanScope.ProtoReflect.Descriptor instead.
func (*ScanScope) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{2}
}

func (x *ScanScope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ScanScope) GetIncludeNamespaces() []string {
	if x != nil {
		return x.IncludeNamespaces
	}
	return nil
}

func (x *ScanScope) GetExcludeNamespaces() []string {
	if x != nil {
		return x.ExcludeNamespaces
	}
	return nil
}

func (x *ScanScope) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

func (x *ScanScope) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *ScanScope) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *ScanScope) GetAnalyzers() []string {
	if x != nil {
		return x.Analyzers
	}
	return nil
}

func (x *ScanScope) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *ScanScope) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type ResourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_api_v1_sre_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRef) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Issue struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace             string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind                  string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                  string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	TargetUid             string                 `protobuf:"bytes,5,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	TargetResourceVersion string                 `protobuf:"bytes,6,opt,name=target_resource_version,json=targetResourceVersion,proto3" json:"target_resource_version,omitempty"`
	Severity              string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	Category              string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Summary               string                 `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`
	Details               string                 `protobuf:"bytes,10,opt,name=details,proto3" json:"details,omitempty"`
	LogsSnippet           string                 `protobuf:"bytes,11,opt,name=logs_snippet,json=logsSnippet,proto3" json:"logs_snippet,omitempty"`
	Events                []string               `protobuf:"bytes,12,rep,name=events,proto3" json:"events,omitempty"`
	SpecSnippet           string                 `protobuf:"bytes,13,opt,name=spec_snippet,json=specSnippet,proto3" json:"spec_snippet,omitempty"`
	FirstObserved         string                 `protobuf:"bytes,14,opt,name=first_observed,json=firstObserved,proto3" json:"first_observed,omitempty"`
	LastObserved          string                 `protobuf:"bytes,15,opt,name=last_observed,json=lastObserved,proto3" json:"last_observed,omitempty"`
	Parent                *ResourceRef           `protobuf:"bytes,16,opt,name=parent,proto3" json:"parent,omitempty"`
	DocsUrl               string                 `protobuf:"bytes,17,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`
	RedactedCount         int32                  `protobuf:"varint,18,opt,name=redacted_count,json=redactedCount,proto3" json:"redacted_count,omitempty"`
	RedactedFields        []string               `protobuf:"bytes,19,rep,name=redacted_fields,json=redactedFields,proto3" json:"redacted_fields,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_api_v1_sre_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{4}
}

func (x *Issue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Issue) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Issue) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Issue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Issue) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

func (x *Issue) GetTargetResourceVersion() string {
	if x != nil {
		return x.TargetResourceVersion
	}
	return ""
}

func (x *Issue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Issue) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Issue) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Issue) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Issue) GetLogsSnippet() string {
	if x != nil {
		return x.LogsSnippet
	}
	return ""
}

func (x *Issue) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Issue) GetSpecSnippet() string {
	if x != nil {
		return x.SpecSnippet
	}
	return ""
}

func (x *Issue) GetFirstObserved() string {
	if x != nil {
		return x.FirstObserved
	}
	return ""
}

func (x *Issue) GetLastObserved() string {
	if x != nil {
		return x.LastObserved
	}
	return ""
}

func (x *Issue) GetParent() *ResourceRef {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Issue) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *Issue) GetRedactedCount() int32 {
	if x != nil {
		return x.RedactedCount
	}
	return 0
}

func (x *Issue) GetRedactedFields() []string {
	if x != nil {
		return x.RedactedFields
	}
	return nil
}

type AnalyzerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DocsUrl       string                 `protobuf:"bytes,4,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`
	ParentKind    string                 `protobuf:"bytes,5,opt,name=parent_kind,json=parentKind,proto3" json:"parent_kind,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IssueCount    int32                  `protobuf:"varint,7,opt,name=issue_count,json=issueCount,proto3" json:"issue_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzerInfo) Reset() {
	*x = AnalyzerInfo{}
	mi := &file_api_v1_sre_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerInfo) ProtoMessage() {}

func (x *AnalyzerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerInfo.ProtoReflect.Descriptor instead.
func (*AnalyzerInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnalyzerInfo) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AnalyzerInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnalyzerInfo) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *AnalyzerInfo) GetParentKind() string {
	if x != nil {
		return x.ParentKind
	}
	return ""
}

func (x *AnalyzerInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AnalyzerInfo) GetIssueCount() int32 {
	if x != nil {
		return x.IssueCount
	}
	return 0
}

type AnalyzerRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *AnalyzerInfo          `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	IssueCount    int32                  `protobuf:"varint,2,opt,name=issue_count,json=issueCount,proto3" json:"issue_count,omitempty"`
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzerRun) Reset() {
	*x = AnalyzerRun{}
	mi := &file_api_v1_sre_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzerRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerRun) ProtoMessage() {}

func (x *AnalyzerRun) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerRun.ProtoReflect.Descriptor instead.
func (*AnalyzerRun) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyzerRun) GetInfo() *AnalyzerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *AnalyzerRun) GetIssueCount() int32 {
	if x != nil {
		return x.IssueCount
	}
	return 0
}

func (x *AnalyzerRun) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *AnalyzerRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AnalyzerRun) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *AnalyzerRun) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Scope         *ScanScope             `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Issues        []*Issue               `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	Analyzers     []*AnalyzerRun         `protobuf:"bytes,4,rep,name=analyzers,proto3" json:"analyzers,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Duration      string                 `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_api_v1_sre_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{7}
}

func (x *ScanResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ScanResponse) GetScope() *ScanScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ScanResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ScanResponse) GetAnalyzers() []*AnalyzerRun {
	if x != nil {
		return x.Analyzers
	}
	return nil
}

func (x *ScanResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ScanResponse) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *ScanResponse) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type ListAnalyzersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Analyzers     []*AnalyzerInfo        `protobuf:"bytes,2,rep,name=analyzers,proto3" json:"analyzers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalyzersResponse) Reset() {
	*x = ListAnalyzersResponse{}
	mi := &file_api_v1_sre_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalyzersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalyzersResponse) ProtoMessage() {}

func (x *ListAnalyzersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalyzersResponse.ProtoReflect.Descriptor instead.
func (*ListAnalyzersResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{8}
}

func (x *ListAnalyzersResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ListAnalyzersResponse) GetAnalyzers() []*AnalyzerInfo {
	if x != nil {
		return x.Analyzers
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_v1_sre_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *QueryRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *QueryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *QueryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ResourceJson  string                 `protobuf:"bytes,5,opt,name=resource_json,json=resourceJson,proto3" json:"resource_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_v1_sre_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{10}
}

func (x *QueryResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *QueryResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *QueryResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *QueryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryResponse) GetResourceJson() string {
	if x != nil {
		return x.ResourceJson
	}
	return ""
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_api_v1_sre_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sre_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sre_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ConfigResponse) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

var File_api_v1_sre_proto protoreflect.FileDescriptor

const file_api_v1_sre_proto_rawDesc = "" +
	"\n" +
	"\x10api/v1/sre.proto\x12\n" +
	"sre.api.v1\"\a\n" +
	"\x05Empty\"\xc6\x02\n" +
	"\vScanRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12-\n" +
	"\x12include_namespaces\x18\x02 \x03(\tR\x11includeNamespaces\x12-\n" +
	"\x12exclude_namespaces\x18\x03 \x03(\tR\x11excludeNamespaces\x12%\n" +
	"\x0elabel_selector\x18\x04 \x01(\tR\rlabelSelector\x12\x14\n" +
	"\x05kinds\x18\x05 \x03(\tR\x05kinds\x12\x14\n" +
	"\x05names\x18\x06 \x03(\tR\x05names\x12\x1c\n" +
	"\tanalyzers\x18\a \x03(\tR\tanalyzers\x12'\n" +
	"\x0fmax_concurrency\x18\b \x01(\x05R\x0emaxConcurrency\x12\x18\n" +
	"\atimeout\x18\t \x01(\tR\atimeout\"\xc4\x02\n" +
	"\tScanScope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12-\n" +
	"\x12include_namespaces\x18\x02 \x03(\tR\x11includeNamespaces\x12-\n" +
	"\x12exclude_namespaces\x18\x03 \x03(\tR\x11excludeNamespaces\x12%\n" +
	"\x0elabel_selector\x18\x04 \x01(\tR\rlabelSelector\x12\x14\n" +
	"\x05kinds\x18\x05 \x03(\tR\x05kinds\x12\x14\n" +
	"\x05names\x18\x06 \x03(\tR\x05names\x12\x1c\n" +
	"\tanalyzers\x18\a \x03(\tR\tanalyzers\x12'\n" +
	"\x0fmax_concurrency\x18\b \x01(\x05R\x0emaxConcurrency\x12\x18\n" +
	"\atimeout\x18\t \x01(\tR\atimeout\"e\n" +
	"\vResourceRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\tR\x03uid\"\xe6\x04\n" +
	"\x05Issue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x05 \x01(\tR\ttargetUid\x126\n" +
	"\x17target_resource_version\x18\x06 \x01(\tR\x15targetResourceVersion\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x18\n" +
	"\asummary\x18\t \x01(\tR\asummary\x12\x18\n" +
	"\adetails\x18\n" +
	" \x01(\tR\adetails\x12!\n" +
	"\flogs_snippet\x18\v \x01(\tR\vlogsSnippet\x12\x16\n" +
	"\x06events\x18\f \x03(\tR\x06events\x12!\n" +
	"\fspec_snippet\x18\r \x01(\tR\vspecSnippet\x12%\n" +
	"\x0efirst_observed\x18\x0e \x01(\tR\rfirstObserved\x12#\n" +
	"\rlast_observed\x18\x0f \x01(\tR\flastObserved\x12/\n" +
	"\x06parent\x18\x10 \x01(\v2\x17.sre.api.v1.ResourceRefR\x06parent\x12\x19\n" +
	"\bdocs_url\x18\x11 \x01(\tR\adocsUrl\x12%\n" +
	"\x0eredacted_count\x18\x12 \x01(\x05R\rredactedCount\x12'\n" +
	"\x0fredacted_fields\x18\x13 \x03(\tR\x0eredactedFields\"\xd7\x01\n" +
	"\fAnalyzerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bdocs_url\x18\x04 \x01(\tR\adocsUrl\x12\x1f\n" +
	"\vparent_kind\x18\x05 \x01(\tR\n" +
	"parentKind\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1f\n" +
	"\vissue_count\x18\a \x01(\x05R\n" +
	"issueCount\"\xce\x01\n" +
	"\vAnalyzerRun\x12,\n" +
	"\x04info\x18\x01 \x01(\v2\x18.sre.api.v1.AnalyzerInfoR\x04info\x12\x1f\n" +
	"\vissue_count\x18\x02 \x01(\x05R\n" +
	"issueCount\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\tR\n" +
	"finishedAt\"\xa0\x02\n" +
	"\fScanResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12+\n" +
	"\x05scope\x18\x02 \x01(\v2\x15.sre.api.v1.ScanScopeR\x05scope\x12)\n" +
	"\x06issues\x18\x03 \x03(\v2\x11.sre.api.v1.IssueR\x06issues\x125\n" +
	"\tanalyzers\x18\x04 \x03(\v2\x17.sre.api.v1.AnalyzerRunR\tanalyzers\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\tR\n" +
	"finishedAt\x12\x1a\n" +
	"\bduration\x18\a \x01(\tR\bduration\"v\n" +
	"\x15ListAnalyzersResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x126\n" +
	"\tanalyzers\x18\x02 \x03(\v2\x18.sre.api.v1.AnalyzerInfoR\tanalyzers\"{\n" +
	"\fQueryRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xa1\x01\n" +
	"\rQueryResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12#\n" +
	"\rresource_json\x18\x05 \x01(\tR\fresourceJson\"X\n" +
	"\x0eConfigResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson2\xd1\x01\n" +
	"\x0fAnalyzerService\x129\n" +
	"\x04Scan\x12\x17.sre.api.v1.ScanRequest\x1a\x18.sre.api.v1.ScanResponse\x12<\n" +
	"\aAnalyze\x12\x17.sre.api.v1.ScanRequest\x1a\x18.sre.api.v1.ScanResponse\x12E\n" +
	"\rListAnalyzers\x12\x11.sre.api.v1.Empty\x1a!.sre.api.v1.ListAnalyzersResponse2\x90\x01\n" +
	"\fQueryService\x12B\n" +
	"\vGetResource\x12\x18.sre.api.v1.QueryRequest\x1a\x19.sre.api.v1.QueryResponse\x12<\n" +
	"\x05Query\x12\x18.sre.api.v1.QueryRequest\x1a\x19.sre.api.v1.QueryResponse2K\n" +
	"\rConfigService\x12:\n" +
	"\tGetConfig\x12\x11.sre.api.v1.Empty\x1a\x1a.sre.api.v1.ConfigResponseB)Z'github.com/kubebee-com/sre/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_sre_proto_rawDescOnce sync.Once
	file_api_v1_sre_proto_rawDescData []byte
)

func file_api_v1_sre_proto_rawDescGZIP() []byte {
	file_api_v1_sre_proto_rawDescOnce.Do(func() {
		file_api_v1_sre_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_sre_proto_rawDesc), len(file_api_v1_sre_proto_rawDesc)))
	})
	return file_api_v1_sre_proto_rawDescData
}

var file_api_v1_sre_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_v1_sre_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: sre.api.v1.Empty
	(*ScanRequest)(nil),           // 1: sre.api.v1.ScanRequest
	(*ScanScope)(nil),             // 2: sre.api.v1.ScanScope
	(*ResourceRef)(nil),           // 3: sre.api.v1.ResourceRef
	(*Issue)(nil),                 // 4: sre.api.v1.Issue
	(*AnalyzerInfo)(nil),          // 5: sre.api.v1.AnalyzerInfo
	(*AnalyzerRun)(nil),           // 6: sre.api.v1.AnalyzerRun
	(*ScanResponse)(nil),          // 7: sre.api.v1.ScanResponse
	(*ListAnalyzersResponse)(nil), // 8: sre.api.v1.ListAnalyzersResponse
	(*QueryRequest)(nil),          // 9: sre.api.v1.QueryRequest
	(*QueryResponse)(nil),         // 10: sre.api.v1.QueryResponse
	(*ConfigResponse)(nil),        // 11: sre.api.v1.ConfigResponse
}
var file_api_v1_sre_proto_depIdxs = []int32{
	3,  // 0: sre.api.v1.Issue.parent:type_name -> sre.api.v1.ResourceRef
	5,  // 1: sre.api.v1.AnalyzerRun.info:type_name -> sre.api.v1.AnalyzerInfo
	2,  // 2: sre.api.v1.ScanResponse.scope:type_name -> sre.api.v1.ScanScope
	4,  // 3: sre.api.v1.ScanResponse.issues:type_name -> sre.api.v1.Issue
	6,  // 4: sre.api.v1.ScanResponse.analyzers:type_name -> sre.api.v1.AnalyzerRun
	5,  // 5: sre.api.v1.ListAnalyzersResponse.analyzers:type_name -> sre.api.v1.AnalyzerInfo
	1,  // 6: sre.api.v1.AnalyzerService.Scan:input_type -> sre.api.v1.ScanRequest
	1,  // 7: sre.api.v1.AnalyzerService.Analyze:input_type -> sre.api.v1.ScanRequest
	0,  // 8: sre.api.v1.AnalyzerService.ListAnalyzers:input_type -> sre.api.v1.Empty
	9,  // 9: sre.api.v1.QueryService.GetResource:input_type -> sre.api.v1.QueryRequest
	9,  // 10: sre.api.v1.QueryService.Query:input_type -> sre.api.v1.QueryRequest
	0,  // 11: sre.api.v1.ConfigService.GetConfig:input_type -> sre.api.v1.Empty
	7,  // 12: sre.api.v1.AnalyzerService.Scan:output_type -> sre.api.v1.ScanResponse
	7,  // 13: sre.api.v1.AnalyzerService.Analyze:output_type -> sre.api.v1.ScanResponse
	8,  // 14: sre.api.v1.AnalyzerService.ListAnalyzers:output_type -> sre.api.v1.ListAnalyzersResponse
	10, // 15: sre.api.v1.QueryService.GetResource:output_type -> sre.api.v1.QueryResponse
	10, // 16: sre.api.v1.QueryService.Query:output_type -> sre.api.v1.QueryResponse
	11, // 17: sre.api.v1.ConfigService.GetConfig:output_type -> sre.api.v1.ConfigResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_sre_proto_init() }
func file_api_v1_sre_proto_init() {
	if File_api_v1_sre_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_sre_proto_rawDesc), len(file_api_v1_sre_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_v1_sre_proto_goTypes,
		DependencyIndexes: file_api_v1_sre_proto_depIdxs,
		MessageInfos:      file_api_v1_sre_proto_msgTypes,
	}.Build()
	File_api_v1_sre_proto = out.File
	file_api_v1_sre_proto_goTypes = nil
	file_api_v1_sre_proto_depIdxs = nil
}
