apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sre

resources:
  - ../../k8s

patches:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: sre-agent
    path: remediation-rbac-patch.yaml
