'use strict';
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const config = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
  const {chromium} = require(config.module);
  const browser = await chromium.launch({headless:true, executablePath:config.chromium || undefined});
  try {
    const context = await browser.newContext({ignoreHTTPSErrors:true, extraHTTPHeaders:{Authorization:'Bearer fixture-owner-a'}, viewport:{width:1440,height:1000}});
    const page = await context.newPage();
    page.setDefaultTimeout(45000);
    const errors=[]; page.on('pageerror', error=>errors.push(error.message));
    await page.goto(config.url);
    await page.waitForFunction(()=>document.querySelectorAll('#scope option').length===2);
    assert.match(await page.locator('#scope').textContent(), /cluster-a/);
    assert.doesNotMatch(await page.locator('#scope').textContent(), /cluster-b/);
    await page.locator('#scope').selectOption('0');
    await page.locator('#incidents button').first().click();
    const queuedResponse = page.waitForResponse(r=>r.request().method()==='POST' && r.url().includes('/investigate?'));
    await page.getByRole('button',{name:'Start a fresh investigation',exact:true}).click();
    const queued = await queuedResponse;
    assert.equal(queued.status(),202,'UI must enqueue agent-owned diagnosis');
    const job = await queued.json();
    assert.ok(job.id,'queued job identity missing');
    await page.waitForFunction(()=>/COMPLETED/.test(document.querySelector('#jobs').textContent));
    await page.locator('#claims .card').first().waitFor();
    const scopeQuery=new URLSearchParams(config.scope);
    const jobs=await (await page.request.get(config.url+'/api/incidents/'+job.incident_id+'/jobs?'+scopeQuery)).json();
    const completed=jobs.find(j=>j.id===job.id);
    assert.equal(completed.state,'COMPLETED');
    assert.ok(completed.result,'diagnosis did not persist a result');
    // Exercise the same clarification UI offered to notification recipients.
    const question={scope:config.scope,id:'browser-clarification',incident_id:job.incident_id,kind:'CLARIFICATION',question:'IMPACT',version:1,status:'PENDING',expires_at:new Date(Date.now()+600000).toISOString()};
    const created=await page.request.post(config.url+'/api/interactions?'+scopeQuery,{data:question});
    assert.equal(created.status(),201);
    await page.getByRole('button',{name:'Refresh',exact:true}).click();
    const clarification=page.locator('#notifications .card').filter({hasText:'browser-clarification'});
    await clarification.getByLabel('Answer code',{exact:true}).selectOption('USER_VISIBLE');
    await clarification.getByRole('button',{name:'Submit clarification',exact:true}).click();
    await clarification.getByRole('heading',{name:'Clarification · ANSWERED',exact:true}).waitFor();
    const questions=await (await page.request.get(config.url+'/api/interactions?'+scopeQuery)).json();
    assert.equal(questions.find(q=>q.id===question.id).answer,'USER_VISIBLE');
    const replay=await page.request.post(config.url+'/api/interactions/'+question.id+'/answer?'+scopeQuery,{data:{version:1,answer:'UNKNOWN'}});
    assert.equal(replay.status(),409);
    const ack=page.locator('#notifications').getByRole('button',{name:'Acknowledge',exact:true}).first();
    await ack.waitFor();
    const ackResponse=page.waitForResponse(r=>r.request().method()==='POST' && r.url().includes('/acknowledge?'));
    await ack.click();
    assert.equal((await ackResponse).status(),200);
    await page.locator('#notifications').getByText('Acknowledged by owner-a',{exact:true}).first().waitFor();
    await page.locator('#incidents button').first().click();
    await page.locator('#claims .card').first().waitFor();
    const card=page.locator('#evidence .card').first();
    await card.getByRole('button',{name:'Cannot verify',exact:true}).click();
    await page.getByText('Saved as attributed feedback; independent review determines diagnostic correctness.',{exact:true}).waitFor();
    await card.getByRole('button',{name:'True',exact:true}).click();
    await card.getByRole('button',{name:'True',exact:true}).and(page.locator('[aria-pressed="true"]')).waitFor();
    await card.getByRole('button',{name:'False',exact:true}).click();
    await page.getByText('Not eligible for reuse. Check disputes, dependencies, and freshness.',{exact:true}).first().waitFor();
    await page.locator('#claims').getByText('Not eligible for reuse. Check disputes, dependencies, and freshness.',{exact:true}).first().waitFor();
    await page.locator('#evidence .card').first().getByText('Engineer feedback history',{exact:true}).click();
    assert.match(await page.locator('#evidence').textContent(), /FALSE/);
    assert.doesNotMatch(await page.locator('body').textContent(), /customer-alice|alice-private|private-workload/);
    if(config.artifacts){fs.mkdirSync(config.artifacts,{recursive:true});await page.screenshot({path:path.join(config.artifacts,'orchestrator-desktop.png'),fullPage:true});}
    await page.setViewportSize({width:390,height:844});
    if(config.artifacts)await page.screenshot({path:path.join(config.artifacts,'orchestrator-mobile.png'),fullPage:true});
    const adminContext=await browser.newContext({ignoreHTTPSErrors:true,extraHTTPHeaders:{Authorization:'Bearer fixture-admin'}});
    const admin=await adminContext.newPage();admin.on('pageerror',error=>errors.push(error.message));
    await admin.goto(config.url);
    await admin.waitForFunction(()=>document.querySelectorAll('#scope option').length===3);
    await admin.locator('#scope').selectOption('0');
    await admin.locator('#setup-panel > summary').click();
    await admin.getByLabel('Environment',{exact:true}).selectOption('STAGING');
    await admin.getByLabel('Platform',{exact:true}).selectOption('SELF_MANAGED');
    await admin.getByLabel('Topology',{exact:true}).selectOption('MULTI_ZONE');
    await admin.getByRole('button',{name:'Save environment context',exact:true}).click();
    await admin.getByText('Environment context saved.',{exact:true}).waitFor();
    assert.equal(await admin.locator('#incidents button').count(),0,'setup authority must not grant incident read');
    const agents=await (await admin.request.get(config.url+'/api/agents?'+new URLSearchParams(config.scope))).json();
    await admin.getByLabel('Agent ID',{exact:true}).fill('browser-extra-collector');
    await admin.getByLabel('Expected Kubernetes cluster UID',{exact:true}).fill(agents[0].cluster_uid);
    await admin.getByRole('button',{name:'Issue one-use enrollment secret',exact:true}).click();
    await admin.waitForFunction(()=>/^[A-Za-z0-9_-]{43}$/.test(document.querySelector('#setup pre')?.textContent||''));
    await adminContext.close();
    assert.deepEqual(errors,[]);
    console.log('Browser passed: queued agent diagnosis, clarification UI and replay rejection, notification acknowledgement, scoped access, all three attributed feedback choices, quarantine reload, privacy canaries, desktop/mobile rendering, setup-only authorization, environment editing and one-use enrollment.');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
