apiVersion: v2
name: sre
description: Unified SRE orchestrator and agent
type: application
version: 0.2.1
appVersion: "sha-d94b738"
dependencies:
  - name: falco
    version: 9.1.0
    repository: https://falcosecurity.github.io/charts
    condition: falco.enabled
